export const PAGES = {
  "bang-tin": {
    slug: "bang-tin",
    icon: "📢",
    short: "Bảng tin",
    title: "Bảng tin & thông báo",
    subtitle: "Tin mới nhất từ cán bộ thôn",
    bg: "#e6efff",
    fg: "#2559d8",
  },
  "danh-ba": {
    slug: "danh-ba",
    icon: "📋",
    short: "Danh bạ",
    title: "Danh bạ",
    subtitle: "Gọi nhanh cán bộ và bà con",
    bg: "#e0f5e9",
    fg: "#2b8552",
  },
  "su-kien": {
    slug: "su-kien",
    icon: "🎉",
    short: "Sự kiện",
    title: "Sự kiện cộng đồng",
    subtitle: "Lịch sinh hoạt của khu dân cư",
    bg: "#fff0dc",
    fg: "#c26a0a",
  },
  "thu-chi": {
    slug: "thu-chi",
    icon: "💰",
    short: "Thu chi",
    title: "Công khai thu chi",
    subtitle: "Minh bạch các khoản thu, chi",
    bg: "#dcf4f2",
    fg: "#0f8a85",
  },
  "dang-ky": {
    slug: "dang-ky",
    icon: "📝",
    short: "Đăng ký",
    title: "Đăng ký sự kiện",
    subtitle: "Đăng ký tham gia trong một phút",
    bg: "#eee8ff",
    fg: "#6d4ad8",
  },
  "phan-anh": {
    slug: "phan-anh",
    icon: "⚠️",
    short: "Phản ánh",
    title: "Gửi phản ánh, kiến nghị",
    subtitle: "Cán bộ thôn sẽ tiếp nhận và xử lý",
    bg: "#ffe7e4",
    fg: "#d64545",
  },
  "vinh-danh": {
    slug: "vinh-danh",
    icon: "🏆",
    short: "Vinh danh",
    title: "Vinh danh, khen thưởng",
    subtitle: "Những tấm gương của khu dân cư",
    bg: "#fff3c9",
    fg: "#a86f00",
  },
  "cho-que": {
    slug: "cho-que",
    icon: "🛒",
    short: "Chợ quê",
    title: "Chợ quê nông sản",
    subtitle: "Mua bán trực tiếp giữa bà con",
    bg: "#ebf5d6",
    fg: "#578512",
  },
  "dat-lich": {
    slug: "dat-lich",
    icon: "📅",
    short: "Đặt lịch",
    title: "Đặt lịch nhà văn hóa",
    subtitle: "Mượn hội trường, bàn ghế, loa đài",
    bg: "#e0f0fb",
    fg: "#1a78b5",
  },
  "quan-tri": {
    slug: "quan-tri",
    icon: "🔐",
    short: "Quản trị",
    title: "Khu vực cán bộ",
    subtitle: "Chỉ dành cho cán bộ được phân công",
    bg: "#edf0f5",
    fg: "#5f6f89",
  },
};

export const TILE_SLUGS = Object.keys(PAGES).filter((s) => s !== "quan-tri");
